{
 "title": "Vouch Attestant",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(vouch_start_time_secs, instance)"
    }
   },
   {
    "name": "provider",
    "label": "Provider",
    "query": {
     "query": "label_values(vouch_client_operation_requests_total{instance=\"$instance\"},provider)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Vouch Status",
   "type": "stat",
   "description": "vouch_ready is set to 1 when Vouch is ready to start attesting, and 0 otherwise. If this number stays at 0 it implies a configuration or connection issue that should be addressed",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vouch_ready{instance=\"$instance\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Validating accounts",
   "type": "bargauge",
   "description": "The number of accounts actively managed by Vouch, broken down by the validator's state.\n\nNote: Unknown accounts are those that Vouch can see in configuration, but cannot be seen on the beacon chain. ",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vouch_accountmanager_accounts_total{instance=\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Vouch Version",
   "type": "stat",
   "description": "The version of Vouch.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(vouch_release{instance=\"$instance\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Sync Committee Validators",
   "type": "stat",
   "description": "The number of validators currently in the sync committee. ",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vouch_synccommitteeverification_current_assigned{instance=\"$instance\"}",
     "legendFormat": "Number Assigned"
    }
   ]
  },
  {
   "title": "Active Multi Clients for Main",
   "type": "stat",
   "description": "Number of beacon clients used for multi-connection strategy on main actions. ",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consensusclient_multi_connections{instance=\"$instance\", name=\"main\", state=\"active\"}",
     "legendFormat": "Number Assigned"
    }
   ]
  },
  {
   "title": "Active Multi Clients for Events",
   "type": "stat",
   "description": "Number of beacon clients used for multi-connection strategy on event actions. ",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consensusclient_multi_connections{instance=\"$instance\", name=\"events\", state=\"active\"}",
     "legendFormat": "Number Assigned"
    }
   ]
  },
  {
   "title": "Latest proposal slot",
   "type": "stat",
   "description": "The latest slot for which Vouch proposed.",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vouch_beaconblockproposal_process_latest_slot{instance=\"$instance\"}",
     "legendFormat": "Number Assigned"
    }
   ]
  },
  {
   "title": "Latest attestation slot",
   "type": "stat",
   "description": "The latest slot for which Vouch attested.",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vouch_attestation_process_latest_slot{instance=\"$instance\"}",
     "legendFormat": "Number Assigned"
    }
   ]
  },
  {
   "title": "Latest attestation aggregate slot",
   "type": "stat",
   "description": "The latest slot for which Vouch produced an aggregate attestation.",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vouch_attestationaggregation_process_latest_slot{instance=\"$instance\"}",
     "legendFormat": "Number Assigned"
    }
   ]
  },
  {
   "title": "Latest proposal preparation slot",
   "type": "stat",
   "description": "The latest slot for which Vouch presented proposal preparations.",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vouch_beaconblockproposal_process_latest_slot{instance=\"$instance\"}",
     "legendFormat": "Number Assigned"
    }
   ]
  },
  {
   "title": "Latest sync committee message slot",
   "type": "stat",
   "description": "The latest slot for which Vouch created a sync committee message.",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vouch_synccommitteemessage_process_latest_slot{instance=\"$instance\"}",
     "legendFormat": "Number Assigned"
    }
   ]
  },
  {
   "title": "Latest sync committee aggregation slot",
   "type": "stat",
   "description": "The latest slot for which Vouch created a sync committee aggregate.",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vouch_synccommitteeaggregation_process_latest_slot{instance=\"$instance\"}",
     "legendFormat": "Number Assigned"
    }
   ]
  },
  {
   "title": "Operation Results",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Client operations succeeded",
     "type": "timeseries",
     "description": "Percentage increase in success operations by operation type and provider.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum(increase(vouch_client_operation_requests_total{result=\"succeeded\",instance=\"$instance\"}[5m])) by (operation, provider)) / (sum(increase(vouch_client_operation_requests_total{instance=\"$instance\"}[5m])) by (operation, provider))",
       "legendFormat": "{{provider}} - {{ operation }}"
      }
     ]
    },
    {
     "title": "Client operations failed",
     "type": "timeseries",
     "description": "Increase in failed operations by operation type and provider.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum(increase(vouch_client_operation_requests_total{result=\"failed\",instance=\"$instance\"}[5m])) by (operation, provider)) / (sum(increase(vouch_client_operation_requests_total{instance=\"$instance\"}[5m])) by (operation, provider))",
       "legendFormat": "{{provider}} - {{ operation }}"
      }
     ]
    },
    {
     "title": "Process request successes",
     "type": "timeseries",
     "description": "Increase in successes of individual Vouch processes.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "increase(vouch_attestation_process_requests_total{instance=\"$instance\",result=\"succeeded\"}[5m]) / increase(vouch_attestation_process_requests_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{ instance }} attestations"
      },
      {
       "expr": "increase(vouch_attestationaggregation_process_requests_total{instance=\"$instance\",result=\"succeeded\"}[5m]) / increase(vouch_attestationaggregation_process_requests_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{instance}} aggregations"
      },
      {
       "expr": "increase(vouch_beaconblockproposal_process_requests_total{instance=\"$instance\",result=\"succeeded\"}[5m]) / increase(vouch_beaconblockproposal_process_requests_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{instance}} proposals"
      },
      {
       "expr": "increase(vouch_beaconcommitteesubscription_process_requests_total{instance=\"$instance\",result=\"succeeded\"}[5m]) / increase(vouch_beaconcommitteesubscription_process_requests_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{instance}} beacon committee subscriptions"
      },
      {
       "expr": "increase(vouch_proposalpreparation_process_requests_total{instance=\"$instance\",result=\"succeeded\"}[5m]) / increase(vouch_beaconcommitteesubscription_process_requests_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{instance}} proposal preparations"
      },
      {
       "expr": "increase(vouch_synccommitteeaggregation_process_requests_total{instance=\"$instance\",result=\"succeeded\"}[5m]) / increase(vouch_synccommitteeaggregation_process_requests_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{instance}} sync committee aggregation"
      },
      {
       "expr": "increase(vouch_synccommitteemessage_process_requests_total{instance=\"$instance\",result=\"succeeded\"}[5m]) / increase(vouch_synccommitteemessage_process_requests_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{instance}} sync committee message"
      },
      {
       "expr": "increase(vouch_synccommitteesubscription_process_requests_total{instance=\"$instance\",result=\"succeeded\"}[5m]) / increase(vouch_synccommitteesubscription_process_requests_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{instance}} sync committee subscription"
      }
     ]
    },
    {
     "title": "Process request failures",
     "type": "timeseries",
     "description": "Increase in failures of individual Vouch processes.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "increase(vouch_attestation_process_requests_total{instance=\"$instance\",result=\"failed\"}[5m]) / increase(vouch_attestation_process_requests_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{ instance }} attestations"
      },
      {
       "expr": "increase(vouch_attestationaggregation_process_requests_total{instance=\"$instance\",result=\"failed\"}[5m]) / increase(vouch_attestationaggregation_process_requests_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{instance}} aggregations"
      },
      {
       "expr": "increase(vouch_beaconblockproposal_process_requests_total{instance=\"$instance\",result=\"failed\"}[5m]) / increase(vouch_beaconblockproposal_process_requests_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{instance}} proposals"
      },
      {
       "expr": "increase(vouch_beaconcommitteesubscription_process_requests_total{instance=\"$instance\",result=\"failed\"}[5m]) / increase(vouch_beaconcommitteesubscription_process_requests_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{instance}} beacon committee subscriptions"
      },
      {
       "expr": "increase(vouch_proposalpreparation_process_requests_total{instance=\"$instance\",result=\"failed\"}[5m]) / increase(vouch_proposalpreparation_process_requests_total{instance=\"$instance\"}[5m])",
       "legendFormat": "__auto"
      },
      {
       "expr": "increase(vouch_synccommitteeaggregation_process_requests_total{instance=\"$instance\",result=\"failed\"}[5m]) / increase(vouch_synccommitteeaggregation_process_requests_total{instance=\"$instance\"}[5m])",
       "legendFormat": "__auto"
      },
      {
       "expr": "increase(vouch_synccommitteemessage_process_requests_total{instance=\"$instance\",result=\"failed\"}[5m]) / increase(vouch_synccommitteemessage_process_requests_total{instance=\"$instance\"}[5m])",
       "legendFormat": "__auto"
      },
      {
       "expr": "increase(vouch_synccommitteesubscription_process_requests_total{instance=\"$instance\",result=\"failed\"}[5m]) / increase(vouch_synccommitteesubscription_process_requests_total{instance=\"$instance\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Beacon committee subscribers and aggregators",
     "type": "timeseries",
     "description": "A subscriber is a particular combination of slot and committee for which Vouch requires a network subscription.\n\nAn aggregator is a particular combination of slot and committee for which Vouch is acting as an attestation aggregator.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "vouch_beaconcommitteesubscription_subscribers_total{instance=\"$instance\"}",
       "legendFormat": "Beacon committee subscribers"
      },
      {
       "expr": "vouch_beaconcommitteesubscription_aggregators_total{instance=\"$instance\"}",
       "legendFormat": "Beacon committee aggregators"
      }
     ]
    },
    {
     "title": "Sync committee subscribers",
     "type": "timeseries",
     "description": "A subscriber is a particular combination of slot and committee for which Vouch requires a network subscription.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "vouch_synccommitteesubscription_subscribers_total{instance=\"$instance\"}",
       "legendFormat": "Sync committee subscribers"
      }
     ]
    },
    {
     "title": "Attestation aggregate coverage ratio",
     "type": "heatmap",
     "description": "The ratio of included to possible attestations in the aggregate.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "sum(increase(vouch_attestationaggregation_coverage_ratio_bucket{instance=\"$instance\"}[384s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Sync committee aggregate coverage ratio",
     "type": "heatmap",
     "description": "The ratio of included to possible messages in the aggregate.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "sum(increase(vouch_synccommitteeaggregation_coverage_ratio_bucket{instance=\"$instance\"}[384s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Beacon block proposals",
     "type": "timeseries",
     "description": "The number of beacon block proposals by method type. ",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(vouch_beaconblockproposal_process_blocks_total{instance=\"$instance\"}[$__interval])) by (method)",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Provider failures",
     "type": "table",
     "description": "Percentage of failures of provider requests.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sort_desc(sum(vouch_client_operation_requests_total{instance=\"$instance\",result=\"failed\"}) by (provider,operation)/sum(vouch_client_operation_requests_total{instance=\"$instance\"}) by (provider,operation))",
       "legendFormat": "{{provider}} {{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Durations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Beacon subscription process duration",
     "type": "heatmap",
     "description": "The time that Vouch takes to carry out beacon committee subscriptions, measured from the time it starts the subscription process to the time it hands off the subscriptions  to be submitted to the beacon nodes.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum(increase(vouch_beaconcommitteesubscription_process_duration_seconds_bucket{instance=\"$instance\"}[384s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Proposal preparation process duration",
     "type": "heatmap",
     "description": "The time that Vouch takes to prepare proposals, measured from the time it starts the proposal preparation process to the time it hands off the proposal preparation to be submitted to the beacon nodes.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "sum(increase(vouch_proposalpreparation_process_duration_seconds_bucket{instance=\"$instance\"}[384s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Proposal process duration",
     "type": "heatmap",
     "description": "The time that Vouch takes to carry out proposals, measured from the time it starts the proposal process to the time it hands off the proposal to be submitted to the beacon nodes.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "sum(increase(vouch_beaconblockproposal_process_duration_seconds_bucket{instance=\"$instance\"}[384s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Attestation process duration",
     "type": "heatmap",
     "description": "The time that Vouch takes to carry out attestations, measured from the time it starts the attestation process to the time it hands off the attestation to be submitted to the beacon nodes.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "sum(increase(vouch_attestation_process_duration_seconds_bucket{instance=\"$instance\"}[384s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Attestation aggregate process duration",
     "type": "heatmap",
     "description": "The time that Vouch takes to carry out attestation aggregations, measured from the time it starts the aggregation process to the time it hands off the attestation aggregate to be submitted to the beacon nodes.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "sum(increase(vouch_attestationaggregation_process_duration_seconds_bucket{instance=\"$instance\"}[384s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Sync committee subscription process duration",
     "type": "heatmap",
     "description": "The time that Vouch takes to carry out sync committee subscriptions, measured from the time it starts the subscription process to the time it hands off the subscriptions  to be submitted to the beacon nodes.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "expr": "sum(increase(vouch_synccommitteesubscription_process_duration_seconds_bucket{instance=\"$instance\"}[384s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Sync committee message process duration",
     "type": "heatmap",
     "description": "The time that Vouch takes to carry out sync committee messages, measured from the time it starts the message process to the time it hands off the sync committee messages to be submitted to the beacon nodes.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "sum(increase(vouch_synccommitteemessage_process_duration_seconds_bucket{instance=\"$instance\"}[384s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Sync committee aggregate process duration",
     "type": "heatmap",
     "description": "The time that Vouch takes to carry out sync committee aggregations, measured from the time it starts the aggregation process to the time it hands off the sync aggregate to be submitted to the beacon nodes.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "sum(increase(vouch_synccommitteeaggregation_process_duration_seconds_bucket{instance=\"$instance\"}[384s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Relay and Builder Bid",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Builder bid absolute delta (ETH)",
     "type": "heatmap",
     "description": "The absolute bid delta obtained by deadline strategy (ETH).",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "sum(increase(vouch_builderbid_strategy_bid_delta_bucket{instance=\"$instance\"}[384s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Builder bid percentage delta",
     "type": "heatmap",
     "description": "The percentage bid delta obtained by deadline strategy.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 47 },
     "targets": [
      {
       "expr": "sum(increase(vouch_builderbid_strategy_bid_pctdelta_bucket{instance=\"$instance\"}[384s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Relay auction block duration",
     "type": "heatmap",
     "description": "The time vouch spends in the auction block operation.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "sum(increase(vouch_relay_auction_block_duration_seconds_bucket{instance=\"$instance\"}[384s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Relay builder bid duration",
     "type": "heatmap",
     "description": "The time vouch spends in the builder bid operation.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 52 },
     "targets": [
      {
       "expr": "sum(increase(vouch_relay_builder_bid_duration_seconds_bucket{instance=\"$instance\"}[384s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Best bid number of relays",
     "type": "heatmap",
     "description": "The number of relays that returned the best bid",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "sum(increase(vouch_beaconblockproposer_best_bid_relays_bucket{instance=\"$instance\"}[384s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Relay validator registrations",
     "type": "heatmap",
     "description": "The time vouch spends in the validator registrations operation.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 57 },
     "targets": [
      {
       "expr": "sum(increase(vouch_relay_validator_registrations_duration_seconds_bucket{instance=\"$instance\"}[384s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Relay execution config duration",
     "type": "heatmap",
     "description": "The time vouch spends in the execution config operation.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "sum(increase(vouch_relay_execution_config_duration_seconds_bucket{instance=\"$instance\"}[384s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Slot Duty Timings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block proposal mark",
     "type": "bargauge",
     "description": "The time in to the slot where the beacon block proposal was broadcast.",
     "gridPos": { "h": 60, "w": 4, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_beaconblockproposal_mark_seconds_bucket{instance=\"$instance\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Attestation mark",
     "type": "bargauge",
     "description": "The time in to the slot where the attestation was broadcast.",
     "gridPos": { "h": 60, "w": 5, "x": 4, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_attestation_mark_seconds_bucket{instance=\"$instance\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Sync committee message mark",
     "type": "bargauge",
     "description": "The time in to the slot where the sync committee messages were broadcast.",
     "gridPos": { "h": 60, "w": 5, "x": 9, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_synccommitteemessage_mark_seconds_bucket{instance=\"$instance\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Aggregate attestation mark",
     "type": "bargauge",
     "description": "The time in to the slot where the aggregate attestations were broadcast.",
     "gridPos": { "h": 60, "w": 5, "x": 14, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_attestationaggregation_mark_seconds_bucket{instance=\"$instance\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Sync committee aggregate mark",
     "type": "bargauge",
     "description": "The time in to the slot where the sync committee aggregates were broadcast.",
     "gridPos": { "h": 60, "w": 5, "x": 19, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_synccommitteeaggregation_mark_seconds_bucket{instance=\"$instance\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Block Receipt Delay",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block receipt delay",
     "type": "heatmap",
     "description": "The time from the start of a slot to the block for that slot being received by Vouch.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "sum(increase(vouch_block_receipt_delay_seconds_bucket{instance=\"$instance\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Client Operation Durations For All Providers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Beacon block proposal time",
     "type": "bargauge",
     "description": "The time taken for the provider to respond with a beacon block proposal.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_client_operation_duration_seconds_bucket{instance=\"$instance\", operation=\"beacon block proposal\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Beacon block submission time",
     "type": "bargauge",
     "description": "The time taken for the providers to accept a submission for a beacon block.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_client_operation_duration_seconds_bucket{instance=\"$instance\",operation=\"submit proposal\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Attestation data time",
     "type": "bargauge",
     "description": "The time taken for the providers to return data for an attestation.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_client_operation_duration_seconds_bucket{instance=\"$instance\",operation=\"attestation data\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Attestation data submission time",
     "type": "bargauge",
     "description": "The time taken for the providers to accept a submission for an attestation.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_client_operation_duration_seconds_bucket{instance=\"$instance\",operation=\"submit attestations\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Attestation aggregation time",
     "type": "bargauge",
     "description": "The time taken for the providers to respond with an aggregate attestation.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_client_operation_duration_seconds_bucket{instance=\"$instance\",operation=\"aggregate attestation\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Attestation aggregation submission time",
     "type": "bargauge",
     "description": "The time taken for the providers to accept a submission for an aggregate attestation.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_client_operation_duration_seconds_bucket{instance=\"$instance\",operation=\"submit aggregate attestations\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Beacon committee subscription time",
     "type": "bargauge",
     "description": "The time vouch spends from starting the beacon committee subscription process up to and including submitting the subscription request.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_beaconcommitteesubscription_process_duration_seconds_bucket{instance=\"$instance\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Beacon committee subscription submission time",
     "type": "bargauge",
     "description": "The time taken for the providers to accept a submission for a beacon committee subscription.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_client_operation_duration_seconds_bucket{instance=\"$instance\",operation=\"submit beacon committee subscription\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Sync committee messages time",
     "type": "bargauge",
     "description": "The time vouch spends from starting the sync committee message process up to and including submitting the sync committee messages.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_synccommitteemessage_process_duration_seconds_bucket{instance=\"$instance\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Sync committee message submission time",
     "type": "bargauge",
     "description": "The time taken for the providers to accept a submission for sync committee messages.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_client_operation_duration_seconds_bucket{instance=\"$instance\",operation=\"submit sync committee messages\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Sync committee aggregation time",
     "type": "bargauge",
     "description": "The time vouch spends from starting the sync committee aggregation process up to and including submitting the sync committee aggregations.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_synccommitteeaggregation_process_duration_seconds_bucket{instance=\"$instance\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Sync committee contribution and proofs submission time",
     "type": "bargauge",
     "description": "The time taken for the providers to accept a submission for sync committee contributions and proofs.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_client_operation_duration_seconds_bucket{instance=\"$instance\",operation=\"submit sync committee contribution and proofs\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Sync committee subscriptions time",
     "type": "bargauge",
     "description": "The time vouch spends from starting the sync committee subscription process up to and including submitting the subscription request.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_synccommitteesubscription_process_duration_seconds_bucket{instance=\"$instance\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Sync committee subscriptions submission time",
     "type": "bargauge",
     "description": "The time taken for the providers to accept a submission for sync committee subscriptions.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_client_operation_duration_seconds_bucket{instance=\"$instance\",operation=\"submit sync committee subscriptions\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Beacon block root response time",
     "type": "bargauge",
     "description": "The time taken for the providers to respond with a beacon block root.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_client_operation_duration_seconds_bucket{instance=\"$instance\",operation=\"beacon block root\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Signed beacon block response time",
     "type": "bargauge",
     "description": "The time taken for the providers to respond with a signed beacon block.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_client_operation_duration_seconds_bucket{instance=\"$instance\",operation=\"signed beacon block\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Sync committee contribution response time",
     "type": "bargauge",
     "description": "The time taken for the providers to respond with a sync committee contribution.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_client_operation_duration_seconds_bucket{instance=\"$instance\",operation=\"sync committee contribution\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Validators response time",
     "type": "bargauge",
     "description": "The time taken for the providers to respond with a list of validators and their current status.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_client_operation_duration_seconds_bucket{instance=\"$instance\",operation=\"validators\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Client Operation Durations For Provider: $provider",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Beacon block proposal time: $provider",
     "type": "bargauge",
     "description": "The time taken for the provider to respond with a beacon block proposal.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_client_operation_duration_seconds_bucket{instance=\"$instance\",provider=~\"$provider\",operation=\"beacon block proposal\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Beacon block submission time: $provider",
     "type": "bargauge",
     "description": "The time taken for the provider to accept a submission for a beacon block.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_client_operation_duration_seconds_bucket{instance=\"$instance\",provider=\"$provider\",operation=\"submit proposal\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Attestation data time: $provider",
     "type": "bargauge",
     "description": "The time taken for the provider to return data for an attestation.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_client_operation_duration_seconds_bucket{instance=\"$instance\",provider=\"$provider\",operation=\"attestation data\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Attestation data submission time: $provider",
     "type": "bargauge",
     "description": "The time taken for the provider to accept a submission for an attestation.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_client_operation_duration_seconds_bucket{instance=\"$instance\",provider=\"$provider\",operation=\"submit attestations\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Attestation aggregation time: $provider",
     "type": "bargauge",
     "description": "The time taken for the provider to respond with an aggregate attestation.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_client_operation_duration_seconds_bucket{instance=\"$instance\",provider=\"$provider\",operation=\"aggregate attestation\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Attestation aggregation submission time: $provider",
     "type": "bargauge",
     "description": "The time taken for the provider to accept a submission for an aggregate attestation.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_client_operation_duration_seconds_bucket{instance=\"$instance\",provider=\"$provider\",operation=\"submit aggregate attestations\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Beacon committee subscription time: All providers",
     "type": "bargauge",
     "description": "The time vouch spends from starting the beacon committee subscription process up to and including submitting the subscription request.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_beaconcommitteesubscription_process_duration_seconds_bucket{instance=\"$instance\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Beacon committee subscription submission time: $provider",
     "type": "bargauge",
     "description": "The time taken for the provider to accept a submission for a beacon committee subscription.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_client_operation_duration_seconds_bucket{instance=\"$instance\",provider=\"$provider\",operation=\"submit beacon committee subscription\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Sync committee messages time: All providers",
     "type": "bargauge",
     "description": "The time vouch spends from starting the sync committee message process up to and including submitting the sync committee messages.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_synccommitteemessage_process_duration_seconds_bucket{instance=\"$instance\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Sync committee message submission time: $provider",
     "type": "bargauge",
     "description": "The time taken for the provider to accept a submission for sync committee messages.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 133 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_client_operation_duration_seconds_bucket{instance=\"$instance\",provider=\"$provider\",operation=\"submit sync committee messages\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Sync committee aggregation time: All providers",
     "type": "bargauge",
     "description": "The time vouch spends from starting the sync committee aggregation process up to and including submitting the sync committee aggregations.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_synccommitteeaggregation_process_duration_seconds_bucket{instance=\"$instance\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Sync committee contribution and proofs submission time: $provider",
     "type": "bargauge",
     "description": "The time taken for the provider to accept a submission for sync committee contributions and proofs.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_client_operation_duration_seconds_bucket{instance=\"$instance\",provider=\"$provider\",operation=\"submit sync committee contribution and proofs\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Sync committee subscriptions time: All providers",
     "type": "bargauge",
     "description": "The time vouch spends from starting the sync committee subscription process up to and including submitting the subscription request.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 149 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_synccommitteesubscription_process_duration_seconds_bucket{instance=\"$instance\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Sync committee subscriptions submission time: $provider",
     "type": "bargauge",
     "description": "The time taken for the provider to accept a submission for sync committee subscriptions.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 149 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_client_operation_duration_seconds_bucket{instance=\"$instance\",provider=\"$provider\",operation=\"submit sync committee subscriptions\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Beacon block root response time: $provider",
     "type": "bargauge",
     "description": "The time taken for the provider to respond with a beacon block root.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_client_operation_duration_seconds_bucket{instance=\"$instance\",provider=\"$provider\",operation=\"beacon block root\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Signed beacon block response time: $provider",
     "type": "bargauge",
     "description": "The time taken for the provider to respond with a signed beacon block.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_client_operation_duration_seconds_bucket{instance=\"$instance\",provider=\"$provider\",operation=\"signed beacon block\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Sync committee contribution response time: $provider",
     "type": "bargauge",
     "description": "The time taken for the provider to respond with a sync committee contribution.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 165 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_client_operation_duration_seconds_bucket{instance=\"$instance\",provider=\"$provider\",operation=\"sync committee contribution\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Validators response time: $provider",
     "type": "bargauge",
     "description": "The time taken for the provider to respond with a list of validators and their current status.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 165 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(vouch_client_operation_duration_seconds_bucket{instance=\"$instance\",provider=\"$provider\",operation=\"validators\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Strategy-Provider Distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Attestation data selection",
     "type": "piechart",
     "description": "Distribution of attestation data strategy selection.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vouch_strategy_operation_used_total{instance=\"$instance\",operation=\"attestation data\"}",
       "legendFormat": "{{ provider }}"
      }
     ]
    },
    {
     "title": "Beacon block proposal selection",
     "type": "piechart",
     "description": "Distribution of beacon block proposal strategy selection.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vouch_strategy_operation_used_total{instance=\"$instance\",operation=\"beacon block proposal\"}",
       "legendFormat": "{{ provider }}"
      }
     ]
    },
    {
     "title": "Aggregate attestation selection",
     "type": "piechart",
     "description": "Distribution of aggregate attestation strategy selection.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vouch_strategy_operation_used_total{instance=\"$instance\",operation=\"aggregate attestation\"}",
       "legendFormat": "{{ provider }}"
      }
     ]
    },
    {
     "title": "Sync committee contribution selection",
     "type": "piechart",
     "description": "Distribution of sync committee contribution strategy selection.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vouch_strategy_operation_used_total{instance=\"$instance\",operation=\"sync committee contribution\"}",
       "legendFormat": "{{ provider }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sync Committee Verification (enabled by `controller.verify-sync-committee-inclusion`)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Sync Committee assigned validators",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "vouch_synccommitteeverification_current_assigned{instance=\"$instance\"}",
       "legendFormat": "Number Assigned"
      }
     ]
    },
    {
     "title": "% of Sync Committee Included in SyncAggregate",
     "type": "timeseries",
     "description": "Cumulative total of sync committee submissions included and missing from the SyncAggregate.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(vouch_synccommitteeverification_found_total{instance=\"$instance\"}) / (sum(vouch_synccommitteeverification_found_total{instance=\"$instance\"}) + sum(vouch_synccommitteeverification_missing_total{instance=\"$instance\"}) + (sum(vouch_synccommitteeverification_mismatches_total{instance=\"$instance\"}) OR on() vector(0)))",
       "legendFormat": "Included in SyncAggregate"
      }
     ]
    },
    {
     "title": "% of Missing from SyncAggregate excluding mismatches",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(vouch_synccommitteeverification_missing_total{instance=\"$instance\"}) / (sum(vouch_synccommitteeverification_found_total{instance=\"$instance\"}) + sum(vouch_synccommitteeverification_missing_total{instance=\"$instance\"}) + (sum(vouch_synccommitteeverification_mismatches_total{instance=\"$instance\"}) OR on() vector(0)))",
       "legendFormat": "Average"
      }
     ]
    },
    {
     "title": "% of Mismatches",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum(vouch_synccommitteeverification_mismatches_total{instance=\"$instance\"}) OR on() vector(0)) / (sum(vouch_synccommitteeverification_found_total{instance=\"$instance\"}) + sum(vouch_synccommitteeverification_missing_total{instance=\"$instance\"}) + (sum(vouch_synccommitteeverification_mismatches_total{instance=\"$instance\"}) OR on() vector(0)))",
       "legendFormat": "Average"
      }
     ]
    },
    {
     "title": "% of Mismatches + Missing",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum(vouch_synccommitteeverification_missing_total{instance=\"$instance\"}) + (sum(vouch_synccommitteeverification_mismatches_total{instance=\"$instance\"}) OR on() vector(0))) / (sum(vouch_synccommitteeverification_found_total{instance=\"$instance\"}) + sum(vouch_synccommitteeverification_missing_total{instance=\"$instance\"}) + (sum(vouch_synccommitteeverification_mismatches_total{instance=\"$instance\"}) OR on() vector(0)))",
       "legendFormat": "Average"
      }
     ]
    },
    {
     "title": "Sync Committee Verification Failures",
     "type": "timeseries",
     "description": "Cumulative total of verification failures by type. ",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(vouch_synccommitteeverification_get_head_failures_total{instance=\"$instance\"})",
       "legendFormat": "Get Head Failure"
      },
      {
       "expr": "sum(vouch_synccommitteeverification_mismatches_total{instance=\"$instance\"})",
       "legendFormat": "Parent Root Mismatches"
      }
     ]
    }
   ]
  },
  {
   "title": "Vouch Internal Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "go_goroutines{source=\"vouch\",instance=\"$instance\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Scheduler",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "vouch_scheduler_jobs_scheduled_total{source=\"vouch\",instance=\"$instance\"}",
       "legendFormat": "{{class}}"
      }
     ]
    },
    {
     "title": "All memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{source=\"vouch\",instance=\"$instance\"}",
       "legendFormat": "Total allocation"
      },
      {
       "expr": "go_memstats_heap_alloc_bytes{source=\"vouch\",instance=\"$instance\"}",
       "legendFormat": "Heap allocation"
      },
      {
       "expr": "go_memstats_mcache_inuse_bytes{source=\"vouch\",instance=\"$instance\"}",
       "legendFormat": "In use (mcache)"
      },
      {
       "expr": "go_memstats_mspan_inuse_bytes{source=\"vouch\",instance=\"$instance\"}",
       "legendFormat": "In use (mspan)"
      }
     ]
    }
   ]
  }
 ]
}